name:                snapstack
version:             0.1.0.0
github:              "fishyfrogface/snapstack"
license:             BSD3
author:              "Camilla Rygh"
copyright:           "2018 Camilla Rygh"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/snapstack#readme>

dependencies:
- base >= 4.7 && < 5
- snap-core >= 1.0 && < 1.1
- snap-server >= 1.0 && < 1.2

ghc-options:
- -Wall
- -fwarn-tabs
- -funbox-strict-fields
- -O2

library:
  source-dirs: src

executables:
  snapstack-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - snapstack

tests:
  snapstack-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - snapstack

